### ISSUE TITLE
IP framing LSF is not clear.

### ISSUE THREAD

**Issue by tarxvftech** [M17-Project/M17_spec#56]
(With thanks to Chibill!)

When implementing M17 over IP, the description of the LSF is insufficient.
SYNC words and TAIL are _not_ sent, but current spec leaves SYNC up in the air and the table implies TAIL is included. The only indication we have currently is separated from the table by another table and is not sufficient:

> The fields in Table 3 (**except tail**) form initial LSF.

(Emphasis mine.)

## Tasks

* [x] Correctly describe the LICH/LSF in the IP framing table.
* [x] LSF description should be clear about role of TAIL and when it's used (RF only).
* [x] Be explicit about when SYNCs are included.

Bonus:
~~* [ ] #60~~
